version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/spring-boot-hello/
hooks:
  AfterInstall:
    - location: setup.sh
      timeout: 1200
      runas: root
  ApplicationStart:
    - location: run.sh
      timeout: 1200
      runas: root